---
- name: Gather System Information
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather hardware and system facts
      ansible.builtin.setup:
        gather_subset:
          - all

    - name: Write gathered facts to a file
      ansible.builtin.copy:
        content: |
          {{
            hostvars[inventory_hostname] |
            to_nice_yaml(width=120, sort_keys=true)
          }}
        dest: "{{ inventory_hostname }}_system_info_{{ ansible_date_time.date }}.txt"

    - name: Fetch results file
      fetch:
        src: "{{ inventory_hostname }}_system_info_{{ ansible_date_time.date }}.txt"
        dest: "{{ playbook_dir }}/../gathered_facts/"
        flat: yes
